---
title: "part 2 time series graphs"
output: html_document
date: "2023-05-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
2. Time Series Graphics

In this section of the report, we will be creating time series graphics using various techniques such as time plots, seasonal plots, seasonal subseries plots, and ACF(). These plots will provide insights into the different time series in the dataset and help us understand their characteristics, such as seasonality, trend, and cyclicity. We will also look for unusual observations and changing patterns over time and explore the differences between the series in terms of these features. Additionally, for this analysis, we have decided to focus on three specific time series: US exports of Natural Gas to OECD, US Exports of Crude Oil to OECD, and US exports of Petroleum products to OECD. We will create the same types of graphs for all of these time series, including time plots, seasonal plots, seasonal subseries plots, and ACF plots. These time series span the last ten years from 2013 to 2023. Through these analyses, we aim to gain insights into the seasonality, cyclicity, trend, unusual observations, changing patterns, and differences between these time series, and determine if any of the series resemble a white noise process. By analyzing these time series graphics, we can gain a better understanding of the data and identify any potential patterns or anomalies that may exist within it.

2.1 Dataset

In this section, we will analyze three datasets that pertain to US exports of Crude oil, Petroleum Products, and Natural Gas, all measured in barrels. Prior to converting the data to tsibble format, we performed data cleaning and formatting. To simplify the data, we converted each dataset to have the same structure, with three columns: date, destination country, and the amount exported. After standardizing the format, we converted each dataset to tsibble format. We then filtered the data to only include countries that are part of the OECD and summarized the results based on the amount exported on each date, removing country names and leaving only the date and amount exported. Finally, we merged all three tsibble tables into one by using the left join function and pivoting the data, resulting in a final time series that represents US exports of the three different products in barrels to OECD countries. The tsibble contains three columns: Date, Export Type, and Amount.

```{bash}
library(fpp3)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(tidyr)
library(lubridate)
################################################################################

#Total Crude Oil Exports by Destination


raw_crude_oil <- read_csv("https://raw.githubusercontent.com/edb-313/Energy-trade-forecasting/main/Data/csv/Total%20Crude%20Oil%20Exports%20by%20Destination_EIA.csv", skip = 2,)


#Leaving only country names in column names

names(raw_crude_oil)[-2] <- str_replace_all(names(raw_crude_oil)[-2],
                                            c("U.S. Exports to " = "",
                                              " of Crude Oil \\(Thousand Barrels\\)" = ""))

#Pivoting (switching) columns starting from 2 column to rows

crude_oil <- raw_crude_oil %>% 
  pivot_longer(cols = -Date,
               names_to = 'Destination country',
               values_to = 'Amount of Crude Oil (Thousand Barrels)')



#Filtering out values where Date is 'NA'

crude_oil <- crude_oil %>%
  drop_na(Date) %>%
  mutate(Date = as.Date(Date))

#Fixing date format, replacing 'na' values with 0

crude_oil$Date <- as.Date(crude_oil$Date)
crude_oil$`Amount of Crude Oil (Thousand Barrels)` <- replace_na(crude_oil$`Amount of Crude Oil (Thousand Barrels)`, 0)

#Setting up the tsibble

ts_crude_oil <- crude_oil %>%
  mutate(Date = yearmonth(Date)) %>% 
  as_tsibble(
    index = Date, 
    key = `Destination country`
  )



#OECD Europe Countries vector

oecd_europe <- c("Austria", "Belgium", "Czech Republic", "Denmark", "Estonia",
                 "Finland", "France", "Germany", "Greece", "Hungary", "Iceland",
                 "Ireland", "Italy", "Latvia", "Lithuania", "Luxembourg",
                 "Netherlands", "Norway", "Poland", "Portugal", "Slovak Republic",
                 "Slovenia", "Spain", "Sweden", "Switzerland", "Turkey",
                 "United Kingdom")

#filtering out only relevant values

oecd_crude_oil <- ts_crude_oil %>%
  filter(`Destination country` %in% oecd_europe) %>% 
  filter(Date >= as.Date("2010-01-15"), Date <= as.Date("2023-01-15")) 

oecd_crude_oil
  
oecd_crude_oil_agg <- oecd_crude_oil %>%
  index_by(Date) %>%
  summarize_at(vars(`Amount of Crude Oil (Thousand Barrels)`), sum) %>%
  ungroup()


################################################################################

#Total Oil Products Exports by Destination

raw_oil_prod <- read_csv("https://raw.githubusercontent.com/edb-313/Energy-trade-forecasting/main/Data/csv/Total%20Oil%20Products%20Exports%20by%20Destination_EIA.csv",  skip = 2,)

names(raw_oil_prod)[-2] <- str_replace_all(names(raw_oil_prod)[-2],
                                           c("U.S. Exports to " = "",
                                             " of Total Petroleum Products \\(Thousand Barrels\\)" = ""))
oil_prod <- raw_oil_prod %>% 
  pivot_longer(cols = -Date,
               names_to = 'Destination country',
               values_to = 'Amount of total Petroleum Porducts (Thousand Barrels)')


oil_prod$`Amount of total Petroleum Porducts (Thousand Barrels)` <- replace_na(oil_prod$`Amount of total Petroleum Porducts (Thousand Barrels)`, 0)

oil_prod <- oil_prod %>% 
  drop_na(Date) %>% 
  mutate(Date = as.Date(Date))

ts_oil_prod <- oil_prod %>%
  mutate(Date = yearmonth(Date)) %>% 
  as_tsibble(
    index = Date, 
    key = `Destination country`
  )

oecd_oil_prod <- ts_oil_prod %>% 
  filter(`Destination country` %in% oecd_europe) %>% 
  filter(Date >= as.Date("2010-01-15"), Date <= as.Date("2023-01-15"))

oecd_oil_prod

oecd_oil_prod_agg <- oecd_oil_prod %>%
  index_by(Date) %>%
  summarize_at(vars(`Amount of total Petroleum Porducts (Thousand Barrels)`), sum) %>%
  ungroup()

################################################################################
#Reliance on Russian gas

raw_rel_rusoil <- read_csv("https://raw.githubusercontent.com/edb-313/Energy-trade-forecasting/main/Data/csv/Monthly_Reliance_on_Russian_Oil.csv", skip = 1)

colnames(raw_rel_rusoil)

rel_rusoil <- raw_rel_rusoil %>% 
  pivot_longer(cols = -...1,
               names_to = 'Date',
               values_to = 'Total Oil Imports from Russia / Total Oil Imports (%)')

rel_rusoil <- rel_rusoil %>% 
  rename(Country = ...1) %>% 
  mutate(Date = lubridate::dmy(Date)) %>% 
  select("Date","Country","Total Oil Imports from Russia / Total Oil Imports (%)")


ts_rel_rusoil <- rel_rusoil %>% 
  as_tsibble(
    index = Date,
    key = Country)

oecd_relrus <- ts_rel_rusoil %>%
  filter(Country %in% oecd_europe)

oecd_relrus %>% slice_sample(n=10)

################################################################################
#Total Natural Gas Exports by Destination

raw_nat_gas <- read.csv('https://raw.githubusercontent.com/edb-313/Energy-trade-forecasting/main/Data/csv/Natural%20Gas%20Exports%20by%20Country_EIA.csv',header=TRUE , check.names=FALSE, skip = 2)

# drop columns 2-3, 6-8, 54 and 57-72
raw_nat_gas <- subset(raw_nat_gas, select = -c(2:3, 6:8,54, 57:72))
raw_nat_gas[is.na(raw_nat_gas)] <- 0

#cimbining exports to the same countries

nat_gas <- raw_nat_gas %>%
  mutate(Mexico = `U.S. Natural Gas Pipeline Exports to Mexico (MMcf)` + `Liquefied U.S. Natural Gas Exports by Truck to Mexico (Million Cubic Feet)`,
         Canada = `U.S. Natural Gas Pipeline Exports to Canada (MMcf)` + `Liquefied U.S. Natural Gas Exports by Truck to Canada (Million Cubic Feet)`)

#removing duplicate columns

nat_gas <- nat_gas[, !(names(nat_gas) %in% c('U.S. Natural Gas Pipeline Exports to Mexico (MMcf)',
                                             'Liquefied U.S. Natural Gas Exports by Truck to Mexico (Million Cubic Feet)',
                                             'U.S. Natural Gas Pipeline Exports to Canada (MMcf)',
                                             'Liquefied U.S. Natural Gas Exports by Truck to Canada (Million Cubic Feet)'))]

#cleaning column names

colnames(nat_gas) <- gsub(pattern = ".*(to\\s)", "", colnames(nat_gas))
colnames(nat_gas) <- gsub("\\(.*?\\)", "", colnames(nat_gas))

#pivoting data
gastemp <- nat_gas %>% 
  pivot_longer(cols = -Date,
               names_to = 'Destination country',
               values_to = 'Amount of Natural gas (MMcf)')

#converting to tsibbles

gastemp

#removing n/as in date column, fixing date formatting, fixing values (romoving space in the end)
library(stringr) #for triming the strings

gastemp <- gastemp %>% 
  drop_na(Date) %>% 
  mutate(Date = as.Date(Date)) %>% 
  mutate(`Destination country` = str_trim(`Destination country`))

#identifying duplicate values 

duplicates(gastemp, index = "Date", key = "Destination country")

#summing duplicates 

gastemp <- gastemp %>%
  group_by(Date, `Destination country`) %>%
  summarize_at(vars(`Amount of Natural gas (MMcf)`), sum) %>%
  ungroup() %>% 
  drop_na(Date)

#creating a tsibble

ts_nat_gas <- gastemp %>%
  mutate(Date = yearmonth(Date)) %>% 
  as_tsibble(
    index = Date,
    key = `Destination country`
  )

#filtering only relevant data

oecd_nat_gas <- ts_nat_gas %>%
  filter(`Destination country` %in% oecd_europe) %>% 
  filter(Date >= as.Date("2010-01-15"), Date <= as.Date("2023-01-15"))



oecd_nat_gas_agg <- oecd_nat_gas %>%
  index_by(Date) %>%
  summarize_at(vars(`Amount of Natural gas (MMcf)`), sum) %>%
  ungroup()

oecd_nat_gas_agg <- oecd_nat_gas_agg %>% 
  mutate(`Amount of Natural gas (BOE)` = `Amount of Natural gas (MMcf)` * 1000 / 6000 )

oecd_nat_gas_agg <- oecd_nat_gas_agg %>% 
  select(Date, `Amount of Natural gas (BOE)`)

oecd_nat_gas_agg

################################################################################

oecd_merged <- left_join(oecd_nat_gas_agg, oecd_oil_prod_agg, by = "Date") %>%
  left_join(oecd_crude_oil_agg, by = "Date")

total_exp_oecd <- oecd_merged %>%
  pivot_longer(cols = -Date, names_to = "Export Type", values_to = "Amount")



```


2.2 Time Series Plots

Firstly, we will examine a general overview of the three products: US exports of Crude Oil, Petroleum Products, and Natural Gas to OECD countries in barrels over the last ten years. This analysis will provide us with an understanding of the overall trend and magnitude of the exports. By examining the trend, we can identify any significant changes in the exports over the years and evaluate the magnitude to determine which product has the highest export value. This overview will be a crucial step before we dive deeper into the individual time series of each product.
## Including Plots

The graph below reveals significant growth in Crude oil and Natural gas exports since around 2015, with a clear year-on-year increase in both goods, indicating a noticeable trend. Moreover, it appears that the time series for these two products are non-stationary, possibly suggesting the presence of a trend, seasonality, or both. In 2022/2023, Crude oil and Natural gas exports reached their peak, with crude oil almost 60,000 and natural gas around 40,000. Conversely, the time series for Petroleum products appears to be stationary, with a slight increasing trend that may require further analysis.

```{Overview of Time series}


total_exp_oecd %>% ggplot(
 aes(Date,Amount,color = `Export Type`)) +
   geom_line()+
   labs(x = "Date", y = "Amount")+
  theme(legend.position = "bottom")

```
In the graph below, we have plotted each exported product separately to provide a better picture of each time series. The data shows that crude oil exports began in 2016 with lower amounts initially, but within a few years, exports boomed. Since 2016, there has been a significant positive trend, possibly with seasonality. In 2020, crude oil exports reached a peak of around 50,000 barrels. Then, due to the COVID-19 pandemic, exports decreased for two years. However, in the beginning of 2022, exports increased significantly, most likely due to the Russian invasion in Ukraine. Currently, exports of crude oil are at a peak, reaching almost 60,000 barrels.

Looking at natural gas exports, we can see that the US did not export to OECD countries until after 2016, when low amounts of natural gas were first exported. In 2018, exports increased significantly, reaching their first peak in 2020. We can see a similar positive trend and possible seasonality as in the crude oil graph. During the COVID-19 pandemic, exports decreased significantly, but again, after the Russian invasion, exports increased significantly, reaching 40,000 barrels. This suggests that OECD countries stopped buying natural gas from Russia.

Finally, looking at petroleum product exports, we can see some fluctuations since 2010, but no clear trend. Seasonality may exist. The changes during COVID-19 and after the Russian invasion were not as significant as in the other two graphs.




```{Overview by product}
total_exp_oecd %>%  
  ggplot(aes(Date, Amount, color = `Export Type`)) +
  geom_line()+
  labs(x = "Date", y = "Amount")+
  theme(legend.position = "bottom") +
  facet_wrap(~`Export Type`, ncol = 1)
```

